// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {XochiZKPVerifier} from "../src/XochiZKPVerifier.sol";
import {XochiZKPOracle} from "../src/XochiZKPOracle.sol";
import {IXochiZKPOracle} from "../src/interfaces/IXochiZKPOracle.sol";
import {ProofTypes} from "../src/libraries/ProofTypes.sol";

/// @title Integration tests using real UltraHonk proofs generated by bb
/// @notice These tests deploy the generated HonkVerifier contracts and verify
///         actual ZK proofs from the Noir circuits, end-to-end.
contract IntegrationTest is Test {
    XochiZKPVerifier internal verifier;
    XochiZKPOracle internal oracle;

    address internal owner = makeAddr("owner");
    address internal alice = makeAddr("alice");
    address internal publisher = makeAddr("publisher");

    /// @dev Address baked into compliance/risk_score proof fixtures as the submitter.
    ///      Oracle enforces submitter == msg.sender, so oracle tests must prank as this address.
    address internal constant FIXTURE_SUBMITTER = address(0xdead);

    /// @dev Must match the config_hash baked into the compliance proof fixture.
    ///      This is pedersen_hash([100, 0, 0, 0, 0, 0, 0, 0]) -- the weight config
    ///      used in the test witness (single provider, weight=100).
    bytes32 internal constant FIXTURE_CONFIG_HASH = 0x18574f427f33c6c77af53be06544bd749c9a1db855599d950af61ea613df8405;

    /// @dev Must match the provider_set_hash baked into the compliance proof fixture.
    bytes32 internal constant FIXTURE_PROVIDER_SET_HASH =
        0x14b6becf762f80a24078e62fc9a7eca246b8e406d19962dda817b173f30a94b2;

    /// @dev Merkle root from the membership fixture
    /// (submitter=0xdead bound to set_id=1, salt=0, index=0)
    bytes32 internal constant FIXTURE_MEMBERSHIP_ROOT =
        0x1d7de002251083fdc312a329d46abde0680cbccc27935c33815c18b1beb3da8c;

    /// @dev Merkle root from the non_membership fixture
    /// (submitter=0xdead, set={0x100, 0x10000}, set_id=1, salt=0)
    bytes32 internal constant FIXTURE_NON_MEMBERSHIP_ROOT =
        0x138f818fd4f2eec91e4fd93e14bcc47bc06a3ba333e5a2e7795d0beb752d247c;

    /// @dev Credential root from the attestation fixture
    /// (provider_id=42, submitter=0xdead, KYC basic, attribute=999, expiry=2000000000)
    bytes32 internal constant FIXTURE_TIER_MERKLE_ROOT =
        0x24ce58f9ed6ca066d25f66b15b0eb1dccebe6e457f5aa0fcd353d82d539f5ed5;

    /// @dev Provider id used in the attestation fixture
    uint256 internal constant FIXTURE_PROVIDER_ID = 42;

    function setUp() public {
        verifier = new XochiZKPVerifier(owner);
        oracle = new XochiZKPOracle(address(verifier), owner, FIXTURE_CONFIG_HASH);

        // Deploy all generated verifiers and register them
        string[6] memory circuits =
            ["compliance", "risk_score", "pattern", "attestation", "membership", "non_membership"];
        uint8[6] memory types = [
            ProofTypes.COMPLIANCE,
            ProofTypes.RISK_SCORE,
            ProofTypes.PATTERN,
            ProofTypes.ATTESTATION,
            ProofTypes.MEMBERSHIP,
            ProofTypes.NON_MEMBERSHIP
        ];

        vm.startPrank(owner);
        for (uint256 i; i < 6; i++) {
            address v = _deployGeneratedVerifier(circuits[i]);
            verifier.setVerifierInitial(types[i], v);
        }

        // Register merkle roots needed by membership/non_membership fixtures
        oracle.registerMerkleRoot(FIXTURE_MEMBERSHIP_ROOT);
        oracle.registerMerkleRoot(FIXTURE_NON_MEMBERSHIP_ROOT);

        // Register reporting threshold needed by pattern fixture (10000)
        oracle.registerReportingThreshold(bytes32(uint256(10000)));

        // ATTESTATION fixtures use the per-provider credentials tree (post C-1 redesign)
        oracle.setProviderPublisher(FIXTURE_PROVIDER_ID, publisher);

        vm.stopPrank();

        // Warp BEFORE publishing the credential root so the root's TTL aligns with the
        // proof timestamp baked into the fixtures (1700000000).
        vm.warp(1700000000);

        vm.prank(publisher);
        oracle.publishCredentialRoot(FIXTURE_PROVIDER_ID, FIXTURE_TIER_MERKLE_ROOT, "");
    }

    // -------------------------------------------------------------------------
    // End-to-end: real proof verification
    // -------------------------------------------------------------------------

    function test_realProof_compliance_verifies() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        bool valid = verifier.verifyProof(ProofTypes.COMPLIANCE, proof, publicInputs);
        assertTrue(valid);
    }

    function test_realProof_compliance_submitAndCheck() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        vm.prank(FIXTURE_SUBMITTER);
        IXochiZKPOracle.ComplianceAttestation memory att = oracle.submitCompliance(
            0, // jurisdiction EU (matches fixture)
            ProofTypes.COMPLIANCE,
            proof,
            publicInputs,
            FIXTURE_PROVIDER_SET_HASH
        );

        assertEq(att.subject, FIXTURE_SUBMITTER);
        assertEq(att.jurisdictionId, 0);
        assertTrue(att.meetsThreshold);
        assertEq(att.providerSetHash, FIXTURE_PROVIDER_SET_HASH);
        assertEq(att.verifierUsed, verifier.getVerifier(ProofTypes.COMPLIANCE));

        // checkCompliance should return valid
        (bool valid,) = oracle.checkCompliance(FIXTURE_SUBMITTER, 0);
        assertTrue(valid);

        // Historical proof should be retrievable
        IXochiZKPOracle.ComplianceAttestation memory historical =
            oracle.getHistoricalProof(oracle.computeProofHash(proof, ProofTypes.COMPLIANCE));
        assertEq(historical.subject, FIXTURE_SUBMITTER);
    }

    function test_realProof_compliance_replayReverts() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");
        bytes32 expectedHash = oracle.computeProofHash(proof, ProofTypes.COMPLIANCE);

        vm.prank(FIXTURE_SUBMITTER);
        oracle.submitCompliance(0, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);

        // Same proof should be rejected
        vm.prank(FIXTURE_SUBMITTER);
        vm.expectRevert(abi.encodeWithSelector(XochiZKPOracle.ProofAlreadyUsed.selector, expectedHash));
        oracle.submitCompliance(0, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);
    }

    function test_realProof_compliance_wrongJurisdictionReverts() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        // Fixture has jurisdiction_id=0 (EU), try submitting as US (1)
        vm.prank(FIXTURE_SUBMITTER);
        vm.expectRevert(XochiZKPOracle.PublicInputMismatch.selector);
        oracle.submitCompliance(1, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);
    }

    function test_realProof_compliance_corruptedProofFails() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");

        // Corrupt one byte of the proof
        proof[42] = proof[42] ^ 0xff;

        // Corrupted proof should revert (verifier reverts on invalid proofs)
        vm.prank(FIXTURE_SUBMITTER);
        vm.expectRevert();
        oracle.submitCompliance(0, ProofTypes.COMPLIANCE, proof, publicInputs, FIXTURE_PROVIDER_SET_HASH);
    }

    // -------------------------------------------------------------------------
    // End-to-end: risk_score proof
    // -------------------------------------------------------------------------

    function test_realProof_riskScore_verifies() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("risk_score");
        bool valid = verifier.verifyProof(ProofTypes.RISK_SCORE, proof, publicInputs);
        assertTrue(valid);
    }

    function test_realProof_riskScore_submitAndCheck() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("risk_score");
        vm.prank(FIXTURE_SUBMITTER);
        IXochiZKPOracle.ComplianceAttestation memory att =
            oracle.submitCompliance(0, ProofTypes.RISK_SCORE, proof, publicInputs, bytes32(0));
        assertEq(att.subject, FIXTURE_SUBMITTER);
        assertTrue(att.meetsThreshold);
    }

    // -------------------------------------------------------------------------
    // End-to-end: pattern (PATTERN) proof
    // -------------------------------------------------------------------------

    function test_realProof_pattern_verifies() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("pattern");
        bool valid = verifier.verifyProof(ProofTypes.PATTERN, proof, publicInputs);
        assertTrue(valid);
    }

    function test_realProof_pattern_submitAndCheck() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("pattern");
        vm.prank(FIXTURE_SUBMITTER);
        IXochiZKPOracle.ComplianceAttestation memory att =
            oracle.submitCompliance(0, ProofTypes.PATTERN, proof, publicInputs, bytes32(0));
        assertEq(att.subject, FIXTURE_SUBMITTER);
        assertTrue(att.meetsThreshold);
    }

    // -------------------------------------------------------------------------
    // End-to-end: attestation (ATTESTATION) proof
    // -------------------------------------------------------------------------

    function test_realProof_attestation_verifies() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("attestation");
        bool valid = verifier.verifyProof(ProofTypes.ATTESTATION, proof, publicInputs);
        assertTrue(valid);
    }

    function test_realProof_attestation_submitAndCheck() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("attestation");
        vm.prank(FIXTURE_SUBMITTER);
        IXochiZKPOracle.ComplianceAttestation memory att =
            oracle.submitCompliance(0, ProofTypes.ATTESTATION, proof, publicInputs, bytes32(0));
        assertEq(att.subject, FIXTURE_SUBMITTER);
        assertTrue(att.meetsThreshold);
    }

    // -------------------------------------------------------------------------
    // End-to-end: membership proof
    // -------------------------------------------------------------------------

    function test_realProof_membership_verifies() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("membership");
        bool valid = verifier.verifyProof(ProofTypes.MEMBERSHIP, proof, publicInputs);
        assertTrue(valid);
    }

    function test_realProof_membership_submitAndCheck() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("membership");
        vm.prank(FIXTURE_SUBMITTER);
        IXochiZKPOracle.ComplianceAttestation memory att =
            oracle.submitCompliance(0, ProofTypes.MEMBERSHIP, proof, publicInputs, bytes32(0));
        assertEq(att.subject, FIXTURE_SUBMITTER);
        assertTrue(att.meetsThreshold);
    }

    // -------------------------------------------------------------------------
    // End-to-end: non_membership proof
    // -------------------------------------------------------------------------

    function test_realProof_nonMembership_verifies() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("non_membership");
        bool valid = verifier.verifyProof(ProofTypes.NON_MEMBERSHIP, proof, publicInputs);
        assertTrue(valid);
    }

    function test_realProof_nonMembership_submitAndCheck() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("non_membership");
        vm.prank(FIXTURE_SUBMITTER);
        IXochiZKPOracle.ComplianceAttestation memory att =
            oracle.submitCompliance(0, ProofTypes.NON_MEMBERSHIP, proof, publicInputs, bytes32(0));
        assertEq(att.subject, FIXTURE_SUBMITTER);
        assertTrue(att.meetsThreshold);
    }

    // -------------------------------------------------------------------------
    // Frozen-Heart variant tests
    //
    // Background: the "Frozen Heart" class of ZK soundness bugs (TrailOfBits, 2022)
    // affected multiple PLONK implementations where the Fiat-Shamir transcript
    // omitted public inputs from the challenge derivation. A malicious prover could
    // forge proofs for arbitrary public inputs by reusing a valid proof against a
    // different statement.
    //
    // bb's UltraHonk verifier hashes publicInputs + VK_HASH into the transcript via
    // ZKTranscriptLib.generateTranscript. These tests lock that property in: take a
    // real proof, mutate ONE byte of publicInputs, and confirm the verifier rejects.
    // If a future bb upgrade ever regresses on transcript safety, these tests fail
    // immediately.
    //
    // Each circuit is tested with its own fixture; the mutation targets a different
    // semantic field per circuit so the suite covers diverse public-input layouts.
    // -------------------------------------------------------------------------

    function _flipBitAt(bytes memory data, uint256 byteIndex, uint8 bit) internal pure returns (bytes memory) {
        bytes memory copy = new bytes(data.length);
        for (uint256 i; i < data.length; i++) {
            copy[i] = data[i];
        }
        copy[byteIndex] = bytes1(uint8(copy[byteIndex]) ^ uint8(1 << bit));
        return copy;
    }

    function test_frozenHeart_compliance_publicInputMutation() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");
        // Sanity: original verifies
        assertTrue(verifier.verifyProof(ProofTypes.COMPLIANCE, proof, publicInputs));

        // Mutate jurisdiction_id (publicInputs[31] is the LSB of the first 32-byte field)
        bytes memory tampered = _flipBitAt(publicInputs, 31, 0);

        // bb's verifier reverts on a failed cryptographic check (SumcheckFailed,
        // ShpleminiFailed, or PairingFailed). Either revert or false-return is acceptable
        // here -- both prove the transcript binds the public inputs.
        try verifier.verifyProof(ProofTypes.COMPLIANCE, proof, tampered) returns (bool valid) {
            assertFalse(valid, "tampered publicInputs verified -- TRANSCRIPT IS BROKEN");
        } catch {
            // Revert is acceptable
        }
    }

    function test_frozenHeart_riskScore_publicInputMutation() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("risk_score");
        assertTrue(verifier.verifyProof(ProofTypes.RISK_SCORE, proof, publicInputs));

        // Mutate the result field (index 4 of 8 -- byte offset 128, LSB at 159)
        bytes memory tampered = _flipBitAt(publicInputs, 159, 0);

        try verifier.verifyProof(ProofTypes.RISK_SCORE, proof, tampered) returns (bool valid) {
            assertFalse(valid, "tampered publicInputs verified -- TRANSCRIPT IS BROKEN");
        } catch { /* revert acceptable */ }
    }

    function test_frozenHeart_pattern_publicInputMutation() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("pattern");
        assertTrue(verifier.verifyProof(ProofTypes.PATTERN, proof, publicInputs));

        // Mutate the analysis_type field (index 0 -- byte offset 31)
        bytes memory tampered = _flipBitAt(publicInputs, 31, 0);

        try verifier.verifyProof(ProofTypes.PATTERN, proof, tampered) returns (bool valid) {
            assertFalse(valid, "tampered publicInputs verified -- TRANSCRIPT IS BROKEN");
        } catch { /* revert acceptable */ }
    }

    function test_frozenHeart_attestation_publicInputMutation() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("attestation");
        assertTrue(verifier.verifyProof(ProofTypes.ATTESTATION, proof, publicInputs));

        // Mutate provider_id (index 0)
        bytes memory tampered = _flipBitAt(publicInputs, 31, 0);

        try verifier.verifyProof(ProofTypes.ATTESTATION, proof, tampered) returns (bool valid) {
            assertFalse(valid, "tampered publicInputs verified -- TRANSCRIPT IS BROKEN");
        } catch { /* revert acceptable */ }
    }

    function test_frozenHeart_membership_publicInputMutation() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("membership");
        assertTrue(verifier.verifyProof(ProofTypes.MEMBERSHIP, proof, publicInputs));

        // Mutate is_member field (index 3 -- byte offset 96, LSB at 127)
        bytes memory tampered = _flipBitAt(publicInputs, 127, 0);

        try verifier.verifyProof(ProofTypes.MEMBERSHIP, proof, tampered) returns (bool valid) {
            assertFalse(valid, "tampered publicInputs verified -- TRANSCRIPT IS BROKEN");
        } catch { /* revert acceptable */ }
    }

    function test_frozenHeart_nonMembership_publicInputMutation() public {
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("non_membership");
        assertTrue(verifier.verifyProof(ProofTypes.NON_MEMBERSHIP, proof, publicInputs));

        // Mutate is_non_member field (index 3 -- LSB at 127)
        bytes memory tampered = _flipBitAt(publicInputs, 127, 0);

        try verifier.verifyProof(ProofTypes.NON_MEMBERSHIP, proof, tampered) returns (bool valid) {
            assertFalse(valid, "tampered publicInputs verified -- TRANSCRIPT IS BROKEN");
        } catch { /* revert acceptable */ }
    }

    function test_frozenHeart_proofMutation_compliance() public {
        // Symmetric test: mutating the proof bytes should also fail. Catches the
        // case where the transcript ignores proof commitments (different bug class).
        (bytes memory proof, bytes memory publicInputs) = _loadFixture("compliance");
        assertTrue(verifier.verifyProof(ProofTypes.COMPLIANCE, proof, publicInputs));

        // Mutate a byte in the middle of the proof
        bytes memory tamperedProof = _flipBitAt(proof, proof.length / 2, 0);

        try verifier.verifyProof(ProofTypes.COMPLIANCE, tamperedProof, publicInputs) returns (bool valid) {
            assertFalse(valid, "tampered proof verified -- VERIFIER IS BROKEN");
        } catch { /* revert acceptable */ }
    }

    // -------------------------------------------------------------------------
    // Cross-type proof confusion (verifier layer)
    //
    // The Oracle's proofType-keyed validators reject proofs whose public input
    // count doesn't match. But the deeper guarantee is at the bb-generated
    // verifier layer: each proof type has a unique VK_HASH burned into its
    // verifier, so a proof from circuit A submitted to circuit B's verifier
    // must fail cryptographically. These tests prove that property directly.
    // -------------------------------------------------------------------------

    function test_crossType_complianceProof_rejectedByRiskScoreVerifier() public {
        (bytes memory complianceProof,) = _loadFixture("compliance");
        // Use risk_score's public inputs (different layout, different count)
        (, bytes memory riskInputs) = _loadFixture("risk_score");

        // Submit a compliance proof under proofType=RISK_SCORE. Should fail.
        try verifier.verifyProof(ProofTypes.RISK_SCORE, complianceProof, riskInputs) returns (bool valid) {
            assertFalse(valid, "cross-type proof verified -- VK COLLISION");
        } catch { /* revert from VK mismatch / sumcheck failure is acceptable */ }
    }

    function test_crossType_membershipProof_rejectedByNonMembershipVerifier() public {
        (bytes memory membershipProof,) = _loadFixture("membership");
        (, bytes memory nonMembershipInputs) = _loadFixture("non_membership");

        try verifier.verifyProof(ProofTypes.NON_MEMBERSHIP, membershipProof, nonMembershipInputs) returns (bool valid) {
            assertFalse(valid, "cross-type proof verified -- VK COLLISION");
        } catch { /* revert acceptable */ }
    }

    // -------------------------------------------------------------------------
    // Verifier flat-count vs logical count invariant
    //
    // bb-generated verifiers expose NUMBER_OF_PUBLIC_INPUTS which includes 16
    // pairing-point inputs the prover supplies in the proof itself. The
    // ProofTypes library only knows about the LOGICAL public inputs (the
    // semantic fields the circuit declares as `pub`). The integration must
    // ensure: NUMBER_OF_PUBLIC_INPUTS - PAIRING_POINTS_SIZE == logicalCount.
    //
    // We can't read NUMBER_OF_PUBLIC_INPUTS from a generic IUltraVerifier
    // interface, so we test the constraint indirectly: each generated verifier
    // accepts exactly `expectedPublicInputCount(proofType)` public inputs (per
    // its internal `publicInputs.length != vk.publicInputsSize - PAIRING_POINTS_SIZE`
    // check). If the alignment ever drifts, the round-trip test below fails:
    // the Oracle generates the right-sized inputs, the verifier rejects.
    // -------------------------------------------------------------------------

    function test_invariant_logicalInputCount_matchesAllVerifiers() public {
        // Every fixture verifies cleanly => its logical input count matches
        // the verifier's expected (vk.publicInputsSize - 16). This is implicitly
        // tested by every existing real-proof test, but we make it explicit here.
        string[6] memory circuits =
            ["compliance", "risk_score", "pattern", "attestation", "membership", "non_membership"];
        uint8[6] memory types = [
            ProofTypes.COMPLIANCE,
            ProofTypes.RISK_SCORE,
            ProofTypes.PATTERN,
            ProofTypes.ATTESTATION,
            ProofTypes.MEMBERSHIP,
            ProofTypes.NON_MEMBERSHIP
        ];
        for (uint256 i; i < 6; i++) {
            (bytes memory proof, bytes memory publicInputs) = _loadFixture(circuits[i]);
            // The verifier will revert with InvalidPublicInputLength if the count
            // ProofTypes reports differs from what the verifier expects.
            bool valid = verifier.verifyProof(types[i], proof, publicInputs);
            assertTrue(valid, string.concat("flat-count drift for ", circuits[i]));
            // Sanity: ProofTypes-reported count = publicInputs.length / 32
            assertEq(publicInputs.length / 32, ProofTypes.expectedPublicInputCount(types[i]));
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    function _loadFixture(string memory circuit) internal view returns (bytes memory proof, bytes memory publicInputs) {
        string memory proofPath = string.concat("test/fixtures/", circuit, "/proof");
        string memory inputsPath = string.concat("test/fixtures/", circuit, "/public_inputs");
        proof = vm.readFileBinary(proofPath);
        publicInputs = vm.readFileBinary(inputsPath);
    }

    function _deployGeneratedVerifier(string memory circuit) internal returns (address) {
        string memory contractName = _verifierContractName(circuit);
        string memory artifact = string.concat(circuit, "_verifier.sol:", contractName);
        bytes memory bytecode = vm.getCode(artifact);
        bytes32 salt = keccak256(abi.encodePacked("xochi-test", circuit));
        address deployed;
        assembly {
            deployed := create2(0, add(bytecode, 0x20), mload(bytecode), salt)
        }
        require(deployed != address(0), "verifier deployment failed");
        return deployed;
    }

    function _verifierContractName(string memory circuit) internal pure returns (string memory) {
        if (keccak256(bytes(circuit)) == keccak256("compliance")) return "ComplianceVerifier";
        if (keccak256(bytes(circuit)) == keccak256("risk_score")) return "RiskScoreVerifier";
        if (keccak256(bytes(circuit)) == keccak256("pattern")) return "PatternVerifier";
        if (keccak256(bytes(circuit)) == keccak256("attestation")) return "AttestationVerifier";
        if (keccak256(bytes(circuit)) == keccak256("membership")) return "MembershipVerifier";
        if (keccak256(bytes(circuit)) == keccak256("non_membership")) return "NonMembershipVerifier";
        revert("unknown circuit");
    }
}
